using Microsoft.AspNetCore.Mvc;
using SpotifyTools.Analytics;
using SpotifyTools.Web.DTOs;

namespace SpotifyTools.Web.Controllers;

[ApiController]
[Route("api/[controller]")]
public class ClustersController : ControllerBase
{
    private readonly IAnalyticsService _analyticsService;
    private readonly ILogger<ClustersController> _logger;

    public ClustersController(
        IAnalyticsService analyticsService,
        ILogger<ClustersController> logger)
    {
        _analyticsService = analyticsService;
        _logger = logger;
    }

    /// <summary>
    /// Get all saved clusters
    /// </summary>
    [HttpGet]
    [ProducesResponseType(typeof(List<ClusterDto>), StatusCodes.Status200OK)]
    public async Task<ActionResult<List<ClusterDto>>> GetAllClusters()
    {
        try
        {
            var clusters = await _analyticsService.GetSavedClustersAsync();
            
            var clusterDtos = clusters.Select(c => new ClusterDto
            {
                Id = int.Parse(c.Id),
                Name = c.Name,
                Description = c.Description,
                Genres = c.Genres,
                TrackCount = c.TotalTracks,
                ArtistCount = c.TotalArtists,
                IsFinalized = false, // TODO: Map from SavedCluster entity
                IsAutoGenerated = c.IsAutoGenerated
            }).ToList();

            return Ok(clusterDtos);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error fetching clusters");
            return StatusCode(500, "An error occurred while fetching clusters");
        }
    }

    /// <summary>
    /// Get a single cluster by ID
    /// </summary>
    [HttpGet("{id}")]
    [ProducesResponseType(typeof(ClusterDto), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<ClusterDto>> GetClusterById(int id)
    {
        try
        {
            var cluster = await _analyticsService.GetSavedClusterByIdAsync(id);
            if (cluster == null)
            {
                return NotFound($"Cluster with ID {id} not found");
            }

            var clusterDto = new ClusterDto
            {
                Id = int.Parse(cluster.Id),
                Name = cluster.Name,
                Description = cluster.Description,
                Genres = cluster.Genres,
                TrackCount = cluster.TotalTracks,
                ArtistCount = cluster.TotalArtists,
                IsFinalized = false, // TODO: Map from SavedCluster entity
                IsAutoGenerated = cluster.IsAutoGenerated
            };

            return Ok(clusterDto);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error fetching cluster {ClusterId}", id);
            return StatusCode(500, "An error occurred while fetching cluster");
        }
    }

    /// <summary>
    /// Generate suggested genre clusters
    /// </summary>
    [HttpGet("suggested")]
    [ProducesResponseType(typeof(List<ClusterDto>), StatusCodes.Status200OK)]
    public async Task<ActionResult<List<ClusterDto>>> GetSuggestedClusters(
        [FromQuery] int minTracksPerCluster = 20)
    {
        try
        {
            var clusters = await _analyticsService.SuggestGenreClustersAsync(minTracksPerCluster);
            
            var clusterDtos = clusters.Select(c => new ClusterDto
            {
                Id = 0, // Suggested clusters don't have IDs yet
                Name = c.Name,
                Description = c.Description,
                Genres = c.Genres,
                TrackCount = c.TotalTracks,
                ArtistCount = c.TotalArtists,
                IsFinalized = false,
                IsAutoGenerated = c.IsAutoGenerated
            }).ToList();

            return Ok(clusterDtos);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error generating suggested clusters");
            return StatusCode(500, "An error occurred while generating clusters");
        }
    }

    /// <summary>
    /// Save a new cluster
    /// </summary>
    [HttpPost]
    [ProducesResponseType(typeof(ClusterDto), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<ClusterDto>> SaveCluster([FromBody] ClusterDto clusterDto)
    {
        try
        {
            var cluster = new GenreCluster
            {
                Id = Guid.NewGuid().ToString(),
                Name = clusterDto.Name,
                Description = clusterDto.Description,
                Genres = clusterDto.Genres,
                IsAutoGenerated = clusterDto.IsAutoGenerated
            };

            var savedId = await _analyticsService.SaveClusterAsync(cluster, clusterDto.Name);
            clusterDto.Id = savedId;

            return CreatedAtAction(nameof(GetClusterById), new { id = savedId }, clusterDto);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error saving cluster");
            return StatusCode(500, "An error occurred while saving cluster");
        }
    }

    /// <summary>
    /// Update an existing cluster
    /// </summary>
    [HttpPut("{id}")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult> UpdateCluster(int id, [FromBody] ClusterDto clusterDto)
    {
        try
        {
            var cluster = new GenreCluster
            {
                Id = id.ToString(),
                Name = clusterDto.Name,
                Description = clusterDto.Description,
                Genres = clusterDto.Genres,
                IsAutoGenerated = clusterDto.IsAutoGenerated
            };

            var updated = await _analyticsService.UpdateClusterAsync(id, cluster);
            if (!updated)
            {
                return NotFound($"Cluster with ID {id} not found");
            }

            return Ok(new { message = "Cluster updated successfully" });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error updating cluster {ClusterId}", id);
            return StatusCode(500, "An error occurred while updating cluster");
        }
    }

    /// <summary>
    /// Delete a cluster
    /// </summary>
    [HttpDelete("{id}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult> DeleteCluster(int id)
    {
        try
        {
            var deleted = await _analyticsService.DeleteClusterAsync(id);
            if (!deleted)
            {
                return NotFound($"Cluster with ID {id} not found");
            }

            return NoContent();
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error deleting cluster {ClusterId}", id);
            return StatusCode(500, "An error occurred while deleting cluster");
        }
    }

    /// <summary>
    /// Finalize a cluster (mark as ready for playlist creation)
    /// </summary>
    [HttpPost("{id}/finalize")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult> FinalizeCluster(int id)
    {
        try
        {
            var finalized = await _analyticsService.FinalizeClusterAsync(id);
            if (!finalized)
            {
                return NotFound($"Cluster with ID {id} not found");
            }

            return Ok(new { message = "Cluster finalized successfully" });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error finalizing cluster {ClusterId}", id);
            return StatusCode(500, "An error occurred while finalizing cluster");
        }
    }

    /// <summary>
    /// Create a Spotify playlist from a finalized cluster
    /// </summary>
    [HttpPost("{id}/create-playlist")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult> CreatePlaylistFromCluster(
        int id,
        [FromQuery] bool makePublic = false)
    {
        try
        {
            var playlistId = await _analyticsService.CreatePlaylistFromClusterAsync(id, makePublic);
            
            return Ok(new
            {
                message = "Playlist created successfully",
                spotifyPlaylistId = playlistId
            });
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(ex.Message);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error creating playlist from cluster {ClusterId}", id);
            return StatusCode(500, "An error occurred while creating playlist");
        }
    }
}
