using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SpotifyTools.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddSavedClustersTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "saved_clusters",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Name = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    Description = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    Genres = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: false),
                    PrimaryGenre = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    IsAutoGenerated = table.Column<bool>(type: "boolean", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    UpdatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true),
                    IsFinalized = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_saved_clusters", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_saved_clusters_CreatedAt",
                table: "saved_clusters",
                column: "CreatedAt");

            migrationBuilder.CreateIndex(
                name: "IX_saved_clusters_IsFinalized",
                table: "saved_clusters",
                column: "IsFinalized");

            migrationBuilder.CreateIndex(
                name: "IX_saved_clusters_Name",
                table: "saved_clusters",
                column: "Name");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "saved_clusters");
        }
    }
}
