// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpotifyTools.Data.DbContext;

#nullable disable

namespace SpotifyTools.Data.Migrations
{
    [DbContext(typeof(SpotifyDbContext))]
    [Migration("20260103095757_AddSavedClustersTableSnakeCase")]
    partial class AddSavedClustersTableSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpotifyTools.Domain.Entities.Album", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AlbumType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FirstSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Label")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalTracks")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ReleaseDate");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.Artist", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FirstSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Followers")
                        .HasColumnType("integer");

                    b.Property<string[]>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("artists", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.AudioAnalysis", b =>
                {
                    b.Property<string>("TrackId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TrackKey")
                        .HasColumnType("integer");

                    b.Property<float>("TrackLoudness")
                        .HasColumnType("real");

                    b.Property<int>("TrackMode")
                        .HasColumnType("integer");

                    b.Property<float>("TrackTempo")
                        .HasColumnType("real");

                    b.Property<int>("TrackTimeSignature")
                        .HasColumnType("integer");

                    b.HasKey("TrackId");

                    b.HasIndex("FetchedAt");

                    b.ToTable("audio_analyses", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.AudioAnalysisSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<float>("KeyConfidence")
                        .HasColumnType("real");

                    b.Property<float>("Loudness")
                        .HasColumnType("real");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<float>("ModeConfidence")
                        .HasColumnType("real");

                    b.Property<float>("Start")
                        .HasColumnType("real");

                    b.Property<float>("Tempo")
                        .HasColumnType("real");

                    b.Property<float>("TempoConfidence")
                        .HasColumnType("real");

                    b.Property<int>("TimeSignature")
                        .HasColumnType("integer");

                    b.Property<float>("TimeSignatureConfidence")
                        .HasColumnType("real");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("Tempo");

                    b.HasIndex("TimeSignature");

                    b.HasIndex("TrackId");

                    b.ToTable("audio_analysis_sections", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.AudioFeatures", b =>
                {
                    b.Property<string>("TrackId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("Acousticness")
                        .HasColumnType("real");

                    b.Property<float>("Danceability")
                        .HasColumnType("real");

                    b.Property<float>("Energy")
                        .HasColumnType("real");

                    b.Property<float>("Instrumentalness")
                        .HasColumnType("real");

                    b.Property<int>("Key")
                        .HasColumnType("integer");

                    b.Property<float>("Liveness")
                        .HasColumnType("real");

                    b.Property<float>("Loudness")
                        .HasColumnType("real");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<float>("Speechiness")
                        .HasColumnType("real");

                    b.Property<float>("Tempo")
                        .HasColumnType("real");

                    b.Property<int>("TimeSignature")
                        .HasColumnType("integer");

                    b.Property<float>("Valence")
                        .HasColumnType("real");

                    b.HasKey("TrackId");

                    b.HasIndex("Danceability");

                    b.HasIndex("Energy");

                    b.HasIndex("Key");

                    b.HasIndex("Tempo");

                    b.ToTable("audio_features", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.Playlist", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("FirstSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SnapshotId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SnapshotId");

                    b.ToTable("playlists", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.PlaylistTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("TrackId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AddedAt");

                    b.HasIndex("TrackId");

                    b.HasIndex("PlaylistId", "Position");

                    b.ToTable("playlist_tracks", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.SavedCluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Genres")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsAutoGenerated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PrimaryGenre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsFinalized");

                    b.HasIndex("Name");

                    b.ToTable("saved_clusters", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.SpotifyToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EncryptedRefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserIdentifier")
                        .IsUnique();

                    b.ToTable("spotify_tokens", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.SyncHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumsAdded")
                        .HasColumnType("integer");

                    b.Property<int>("ArtistsAdded")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("MissingPlaylistTrackIds")
                        .HasColumnType("text");

                    b.Property<int>("PlaylistsSynced")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SyncType")
                        .HasColumnType("integer");

                    b.Property<int>("TracksAdded")
                        .HasColumnType("integer");

                    b.Property<int>("TracksUpdated")
                        .HasColumnType("integer");

                    b.Property<string>("UserIdentifier")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Status");

                    b.HasIndex("SyncType");

                    b.ToTable("sync_history", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.Track", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<bool>("Explicit")
                        .HasColumnType("boolean");

                    b.Property<Dictionary<string, object>>("ExtendedMetadata")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("FirstSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Isrc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddedAt");

                    b.HasIndex("Name");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.TrackAlbum", b =>
                {
                    b.Property<string>("TrackId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AlbumId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DiscNumber")
                        .HasColumnType("integer");

                    b.Property<int>("TrackNumber")
                        .HasColumnType("integer");

                    b.HasKey("TrackId", "AlbumId");

                    b.HasIndex("AlbumId");

                    b.ToTable("track_albums", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.TrackArtist", b =>
                {
                    b.Property<string>("TrackId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ArtistId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("TrackId", "ArtistId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("Position");

                    b.ToTable("track_artists", (string)null);
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.AudioAnalysis", b =>
                {
                    b.HasOne("SpotifyTools.Domain.Entities.Track", "Track")
                        .WithOne("AudioAnalysis")
                        .HasForeignKey("SpotifyTools.Domain.Entities.AudioAnalysis", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.AudioAnalysisSection", b =>
                {
                    b.HasOne("SpotifyTools.Domain.Entities.AudioAnalysis", "AudioAnalysis")
                        .WithMany("Sections")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AudioAnalysis");
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.AudioFeatures", b =>
                {
                    b.HasOne("SpotifyTools.Domain.Entities.Track", "Track")
                        .WithOne("AudioFeatures")
                        .HasForeignKey("SpotifyTools.Domain.Entities.AudioFeatures", "TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.PlaylistTrack", b =>
                {
                    b.HasOne("SpotifyTools.Domain.Entities.Playlist", "Playlist")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyTools.Domain.Entities.Track", "Track")
                        .WithMany("PlaylistTracks")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.TrackAlbum", b =>
                {
                    b.HasOne("SpotifyTools.Domain.Entities.Album", "Album")
                        .WithMany("TrackAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyTools.Domain.Entities.Track", "Track")
                        .WithMany("TrackAlbums")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.TrackArtist", b =>
                {
                    b.HasOne("SpotifyTools.Domain.Entities.Artist", "Artist")
                        .WithMany("TrackArtists")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpotifyTools.Domain.Entities.Track", "Track")
                        .WithMany("TrackArtists")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.Album", b =>
                {
                    b.Navigation("TrackAlbums");
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.Artist", b =>
                {
                    b.Navigation("TrackArtists");
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.AudioAnalysis", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.Playlist", b =>
                {
                    b.Navigation("PlaylistTracks");
                });

            modelBuilder.Entity("SpotifyTools.Domain.Entities.Track", b =>
                {
                    b.Navigation("AudioAnalysis");

                    b.Navigation("AudioFeatures");

                    b.Navigation("PlaylistTracks");

                    b.Navigation("TrackAlbums");

                    b.Navigation("TrackArtists");
                });
#pragma warning restore 612, 618
        }
    }
}
