namespace SpotifyTools.Domain.Entities;

/// <summary>
/// Represents a user-saved genre cluster for playlist organization
/// </summary>
public class SavedCluster
{
    /// <summary>
    /// Unique identifier for this saved cluster
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// User-defined or auto-generated name for the cluster
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Optional description of what this cluster represents
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Comma-separated list of genres in this cluster
    /// </summary>
    public string Genres { get; set; } = string.Empty;

    /// <summary>
    /// Primary/dominant genre in the cluster
    /// </summary>
    public string? PrimaryGenre { get; set; }

    /// <summary>
    /// Whether this cluster was auto-generated or manually created
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// When this cluster was created
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

    /// <summary>
    /// When this cluster was last modified
    /// </summary>
    public DateTime? UpdatedAt { get; set; }

    /// <summary>
    /// Whether the user has marked this cluster as finalized for playlist creation
    /// </summary>
    public bool IsFinalized { get; set; }

    /// <summary>
    /// The Spotify playlist ID if a playlist has been created from this cluster
    /// </summary>
    public string? SpotifyPlaylistId { get; set; }

    /// <summary>
    /// When the Spotify playlist was created
    /// </summary>
    public DateTime? PlaylistCreatedAt { get; set; }

    /// <summary>
    /// Helper to get genres as a list
    /// </summary>
    public List<string> GetGenresList()
    {
        return string.IsNullOrEmpty(Genres)
            ? new List<string>()
            : Genres.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries).ToList();
    }

    /// <summary>
    /// Helper to set genres from a list
    /// </summary>
    public void SetGenresList(List<string> genres)
    {
        Genres = string.Join(",", genres);
    }
}
