namespace SpotifyTools.Analytics;

/// <summary>
/// Represents a cluster of related genres that can be used for playlist organization
/// </summary>
public class GenreCluster
{
    /// <summary>
    /// Unique identifier for this cluster
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Display name for the cluster (e.g., "Rock & Alternative", "Electronic & Dance")
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Brief description of what this cluster represents
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Genres included in this cluster
    /// </summary>
    public List<string> Genres { get; set; } = new();

    /// <summary>
    /// Primary/dominant genre in this cluster (most common)
    /// </summary>
    public string? PrimaryGenre { get; set; }

    /// <summary>
    /// Total number of tracks that would be in this cluster
    /// </summary>
    public int TotalTracks { get; set; }

    /// <summary>
    /// Total number of unique artists in this cluster
    /// </summary>
    public int TotalArtists { get; set; }

    /// <summary>
    /// Average popularity of tracks in this cluster
    /// </summary>
    public double AveragePopularity { get; set; }

    /// <summary>
    /// Percentage of library this cluster represents
    /// </summary>
    public double PercentageOfLibrary { get; set; }

    /// <summary>
    /// Whether this cluster was auto-generated or user-created
    /// </summary>
    public bool IsAutoGenerated { get; set; }
}
