namespace SpotifyTools.Web.DTOs;

public class ClusterDto
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string? Description { get; set; }
    public List<string> Genres { get; set; } = new();
    public int TrackCount { get; set; }
    public int ArtistCount { get; set; }
    public bool IsFinalized { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? SpotifyPlaylistId { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
}
